import {
  CardRace,
  CardType,
  FrameType,
  LinkMarker,
  MonsterAttribute,
} from '@prisma/client';

export const TYPE_MAPPING: Record<string, CardType> = {
  'Effect Monster': CardType.EFFECT_MONSTER,
  'Fusion Monster': CardType.FUSION_MONSTER,
  'Flip Effect Monster': CardType.FLIP_EFFECT_MONSTER,
  'Flip Tuner Effect Monster': CardType.FLIP_TUNER_EFFECT_MONSTER,
  'Gemini Monster': CardType.GEMINI_MONSTER,
  'Link Monster': CardType.LINK_MONSTER,
  'Normal Monster': CardType.NORMAL_MONSTER,
  'Normal Tuner Monster': CardType.NORMAL_TUNER_MONSTER,
  'Pendulum Effect Monster': CardType.PENDULUM_EFFECT_MONSTER,
  'Pendulum Effect Fusion Monster': CardType.PENDULUM_EFFECT_FUSION_MONSTER,
  'Pendulum Effect Ritual Monster': CardType.PENDULUM_EFFECT_RITUAL_MONSTER,
  'Pendulum Flip Effect Monster': CardType.PENDULUM_FLIP_EFFECT_MONSTER,
  'Pendulum Normal Monster': CardType.PENDULUM_NORMAL_MONSTER,
  'Pendulum Tuner Effect Monster': CardType.PENDULUM_TUNER_EFFECT_MONSTER,
  'Ritual Effect Monster': CardType.RITUAL_EFFECT_MONSTER,
  'Ritual Monster': CardType.RITUAL_MONSTER,
  'Spell Card': CardType.SPELL_CARD,
  'Spirit Monster': CardType.SPIRIT_MONSTER,
  'Synchro Monster': CardType.SYNCHRO_MONSTER,
  'Synchro Pendulum Effect Monster': CardType.SYNCHRO_PENDULUM_EFFECT_MONSTER,
  'Synchro Tuner Monster': CardType.SYNCHRO_TUNER_MONSTER,
  'Toon Monster': CardType.TOON_MONSTER,
  Token: CardType.TOKEN,
  'Trap Card': CardType.TRAP_CARD,
  'Tuner Monster': CardType.TUNER_MONSTER,
  'Union Effect Monster': CardType.UNION_EFFECT_MONSTER,
  'XYZ Monster': CardType.XYZ_MONSTER,
  'XYZ Pendulum Effect Monster': CardType.XYZ_PENDULUM_EFFECT_MONSTER,
};

export const ATTRIBUTE_MAPPING: Record<string, MonsterAttribute> = {
  DARK: MonsterAttribute.DARK,
  DIVINE: MonsterAttribute.DIVINE,
  EARTH: MonsterAttribute.EARTH,
  FIRE: MonsterAttribute.FIRE,
  LIGHT: MonsterAttribute.LIGHT,
  WATER: MonsterAttribute.WATER,
  WIND: MonsterAttribute.WIND,
};

export const LINK_MARKER_MAPPING: Record<string, LinkMarker> = {
  Top: LinkMarker.TOP,
  'Top-Right': LinkMarker.TOP_RIGHT,
  Right: LinkMarker.RIGHT,
  'Bottom-Right': LinkMarker.BOTTOM_RIGHT,
  Bottom: LinkMarker.BOTTOM,
  'Bottom-Left': LinkMarker.BOTTOM_LEFT,
  Left: LinkMarker.LEFT,
  'Top-Left': LinkMarker.TOP_LEFT,
};

export const FRAME_TYPE_MAPPING: Record<string, FrameType> = {
  normal: FrameType.NORMAL,
  effect: FrameType.EFFECT,
  fusion: FrameType.FUSION,
  ritual: FrameType.RITUAL,
  synchro: FrameType.SYNCHRO,
  xyz: FrameType.XYZ,
  normal_pendulum: FrameType.NORMAL_PENDULUM,
  effect_pendulum: FrameType.EFFECT_PENDULUM,
  fusion_pendulum: FrameType.FUSION_PENDULUM,
  ritual_pendulum: FrameType.RITUAL_PENDULUM,
  synchro_pendulum: FrameType.SYNCHRO_PENDULUM,
  xyz_pendulum: FrameType.XYZ_PENDULUM,
  link: FrameType.LINK,
  spell: FrameType.SPELL,
  trap: FrameType.TRAP,
  token: FrameType.TOKEN,
};

export const RACE_MAPPING: Record<string, CardRace> = {
  Aqua: CardRace.AQUA,
  Beast: CardRace.BEAST,
  'Beast-Warrior': CardRace.BEAST_WARRIOR,
  Continuous: CardRace.CONTINUOUS,
  Counter: CardRace.COUNTER,
  'Creator-God': CardRace.CREATOR_GOD,
  Cyberse: CardRace.CYBERSE,
  Dinosaur: CardRace.DINOSAUR,
  'Divine-Beast': CardRace.DIVINE_BEAST,
  Dragon: CardRace.DRAGON,
  Equip: CardRace.EQUIP,
  Fairy: CardRace.FAIRY,
  Field: CardRace.FIELD,
  Fiend: CardRace.FIEND,
  Fish: CardRace.FISH,
  Illusion: CardRace.ILLUSION,
  Insect: CardRace.INSECT,
  Machine: CardRace.MACHINE,
  Normal: CardRace.NORMAL,
  Plant: CardRace.PLANT,
  Psychic: CardRace.PSYCHIC,
  Pyro: CardRace.PYRO,
  'Quick-Play': CardRace.QUICK_PLAY,
  Reptile: CardRace.REPTILE,
  Ritual: CardRace.RITUAL,
  Rock: CardRace.ROCK,
  'Sea Serpent': CardRace.SEA_SERPENT,
  Spellcaster: CardRace.SPELLCASTER,
  Thunder: CardRace.THUNDER,
  Warrior: CardRace.WARRIOR,
  'Winged Beast': CardRace.WINGED_BEAST,
  Wyrm: CardRace.WYRM,
  Zombie: CardRace.ZOMBIE,
};
