-- CreateEnum
CREATE TYPE "FrameType" AS ENUM ('EFFECT', 'EFFECT_PENDULUM', 'FUSION', 'FUSION_PENDULUM', 'LINK', 'NORMAL', 'NORMAL_PENDULUM', 'RITUAL', 'RITUAL_PENDULUM', 'SPELL', 'SYNCHRO', 'SYNCHRO_PENDULUM', 'TOKEN', 'TRAP', 'XYZ', 'XYZ_PENDULUM');

-- CreateEnum
CREATE TYPE "CardType" AS ENUM ('EFFECT_MONSTER', 'FLIP_EFFECT_MONSTER', 'FLIP_TUNER_EFFECT_MONSTER', 'FUSION_MONSTER', 'GEMINI_MONSTER', 'LINK_MONSTER', 'NORMAL_MONSTER', 'NORMAL_TUNER_MONSTER', 'PENDULUM_EFFECT_MONSTER', 'PENDULUM_EFFECT_FUSION_MONSTER', 'PENDULUM_EFFECT_RITUAL_MONSTER', 'PENDULUM_FLIP_EFFECT_MONSTER', 'PENDULUM_NORMAL_MONSTER', 'PENDULUM_TUNER_EFFECT_MONSTER', 'RITUAL_EFFECT_MONSTER', 'RITUAL_MONSTER', 'SPELL_CARD', 'SPIRIT_MONSTER', 'SYNCHRO_MONSTER', 'SYNCHRO_PENDULUM_EFFECT_MONSTER', 'SYNCHRO_TUNER_MONSTER', 'TOON_MONSTER', 'TOKEN', 'TRAP_CARD', 'TUNER_MONSTER', 'UNION_EFFECT_MONSTER', 'XYZ_MONSTER', 'XYZ_PENDULUM_EFFECT_MONSTER');

-- CreateEnum
CREATE TYPE "LinkMarker" AS ENUM ('BOTTOM_LEFT', 'BOTTOM_RIGHT', 'BOTTOM', 'LEFT', 'RIGHT', 'TOP_LEFT', 'TOP_RIGHT', 'TOP');

-- CreateEnum
CREATE TYPE "MonsterAttribute" AS ENUM ('DARK', 'DIVINE', 'EARTH', 'FIRE', 'LIGHT', 'WATER', 'WIND');

-- CreateEnum
CREATE TYPE "CardRace" AS ENUM ('AQUA', 'BEAST', 'BEAST_WARRIOR', 'CONTINUOUS', 'COUNTER', 'CREATOR_GOD', 'CYBERSE', 'DINOSAUR', 'DIVINE_BEAST', 'DRAGON', 'DR_VELLIAN_C', 'EQUIP', 'FAIRY', 'FIEND', 'FIELD', 'FISH', 'ILLUSION', 'INSECT', 'MACHINE', 'NORMAL', 'PLANT', 'PSYCHIC', 'PYRO', 'QUICK_PLAY', 'REPTILE', 'RITUAL', 'ROCK', 'SEA_SERPENT', 'SPELLCASTER', 'THUNDER', 'WARRIOR', 'WINGED_BEAST', 'WYRM', 'ZOMBIE');

-- CreateTable
CREATE TABLE "Card" (
    "id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "type" "CardType" NOT NULL,
    "frameType" "FrameType" NOT NULL,
    "desc" TEXT NOT NULL,
    "atk" INTEGER,
    "def" INTEGER,
    "level" INTEGER,
    "scale" INTEGER,
    "linkval" INTEGER,
    "linkmarkers" "LinkMarker"[],
    "race" "CardRace",
    "attribute" "MonsterAttribute",
    "archetype" TEXT,
    "image_url" TEXT NOT NULL,
    "card_sets" JSONB[],
    "card_prices" JSONB[],
    "banlist_info" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Card_pkey" PRIMARY KEY ("id")
);
